### ISSUE TITLE
Feature: forget password 04(21-23)

### ISSUE THREAD

**Issue by Nkbtemmy** [atlp-rwanda/matadors-rn-medica#13]

**Comment by aimeudoxie** [comment]
**Description**

This issue is about implementing the Forget password screen and OTP verification screen in both Light and Dark mode

**Tasks**

- [x] Build Forget password screen 

- [x] Build OTP verification screen

**Design/Devs Notes**

![Screenshot 2024-05-06 022411](https://github.com/atlp-rwanda/matadors-rn-medica/assets/98123621/c70c422a-5634-4400-91f3-a82ff95903ff)

![Screenshot 2024-05-06 022454](https://github.com/atlp-rwanda/matadors-rn-medica/assets/98123621/8dd3b860-7d80-4f73-a67c-619e4eac0f45)

**Related issues**

- N/A

**Definition of Done**

- created a screen for selecting the Reset password method

- created a screen for entering and re requesting the OTP code for verification

- created both light and dark mode of the screens
